### ISSUE TITLE
npm start throws error under example/express-swagger-example 

### ISSUE THREAD

**Issue by ajaysuwalka** [SystangoTechnologies/swagger-generator-express#1]
```
Response model path does not exist responseModelFullPath-> swagger-generator-express\example\express-swagger-example\src\responseModel\index.js
Response model path does not exist requestModelFullPath-> swagger-generator-express\example\express-swagger-example\src\requestModel\index.js
Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Promise.tap.then.catch.err (swagger-generator-express\example\express-swagger-example\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:123:19)
    at tryCatcher (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (swagger-generator-express\example\express-swagger-example\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

```

**Comment by sumits-systango** [comment]
We'll take a look.

**Comment by Kai-Qiao** [comment]
the error is coursed by the MySQL connection, as the example depends on the MySQL database, if you install and open the MySQL server will be no error,  one suggestion is to remove the database connection from the examples. Using the static file for users will be more friendly.
